image: node:lts-alpine

stages:
  - preparation
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

run_yarn_install:
  stage: preparation
  before_script:
    - yarn -v
  script:
    - yarn

run_unit_tests:
  stage: test
  variables:
    VUE_APP_APP_NAME: $TEST_VUE_APP_APP_NAME
    VUE_APP_API_URL: $TEST_VUE_APP_API_URL
    VUE_APP_AUTH_USERNAME: $TEST_VUE_APP_AUTH_USER_NAME
    VUE_APP_AUTH_PASSWORD: $TEST_VUE_APP_AUTH_PASSWORD
  script:
    - yarn test:unit
