image: node:lts-alpine

stages:
  - preparation
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

run_yarn_install:
  stage: preparation
  before_script:
    - yarn -v
  script:
    - yarn

run_unit_tests:
  stage: test
  script:
    - touch .env.test.local
    - echo VUE_APP_APP_NAME=$TEST_VUE_APP_APP_NAME >> .env
    - echo VUE_APP_API_URL=$TEST_VUE_APP_API_URL >> .env
    - echo VUE_APP_AUTH_USERNAME=$TEST_VUE_APP_AUTH_USER_NAME >> .env
    - echo VUE_APP_AUTH_PASSWORD=$TEST_VUE_APP_AUTH_PASSWORD >> .env
    - cat .env.test.local
    - yarn test:unit
