export const FETCH_ALL_AGENCIES = 'FETCH_ALL_AGENCIES'
export const FETCH_ALL_AGENCIES_SUCCESS = 'FETCH_ALL_AGENCIES_SUCCESS'
export const FETCH_ALL_AGENCIES_ERROR = 'FETCH_ALL_AGENCIES_ERROR'

export const FETCH_ONE_AGENCY = 'FETCH_ONE_AGENCY'
export const FETCH_ONE_AGENCY_SUCCESS = 'FETCH_ONE_AGENCY_SUCCESS'
export const FETCH_ONE_AGENCY_ERROR = 'FETCH_ONE_AGENCY_ERROR'

export const STORE_AGENCY = 'STORE_AGENCY'
export const STORE_AGENCY_SUCCESS = 'STORE_AGENCY_SUCCESS'
export const STORE_AGENCY_ERROR = 'STORE_AGENCY_ERROR'

export const GET_AGENCY_DATA = 'GET_AGENCY_DATA'