export const FETCH_ALL_AGENCIES = 'FETCH_ALL_AGENCIES'
export const FETCH_ALL_AGENCIES_SUCCESS = 'FETCH_ALL_AGENCIES_SUCCESS'
export const FETCH_ALL_AGENCIES_ERROR = 'FETCH_ALL_AGENCIES_ERROR'

export const GET_AGENCY_DATA = 'GET_AGENCY_DATA'