export const FETCH_ALL_ASN = 'FETCH_ALL_ASN'
export const FETCH_ALL_ASN_SUCCESS = 'FETCH_ALL_ASN_SUCCESS'
export const FETCH_ALL_ASN_ERROR = 'FETCH_ALL_ASN_ERROR'

export const STORE_ASN = 'STORE_ASN'
export const STORE_ASN_SUCCESS = 'STORE_ASN_SUCCESS'
export const STORE_ASN_ERROR = 'STORE_ASN_ERROR'

export const FETCH_ONE_ASN = 'FETCH_ONE_ASN'
export const FETCH_ONE_ASN_SUCCESS = 'FETCH_ONE_ASN_SUCCESS'
export const FETCH_ONE_ASN_ERROR = 'FETCH_ONE_ASN_ERROR'

export const UPDATE_ASN = 'UPDATE_ASN'
export const UPDATE_ASN_SUCCESS = 'UPDATE_ASN_SUCCESS'
export const UPDATE_ASN_ERROR = 'UPDATE_ASN_ERROR'

export const DESTROY_ASN = 'DESTROY_ASN'
export const DESTROY_ASN_SUCCESS = 'DESTROY_ASN_SUCCESS'
export const DESTROY_ASN_ERROR = 'DESTROY_ASN_ERROR'

export const GET_ASN_DATA = 'GET_ASN_DATA'
export const GET_ASN_FORM = 'GET_ASN_FORM'
export const SET_ASN_FORM = 'SET_ASN_FORM'
export const RESET_ASN_FORM = 'RESET_ASN_FORM'
