export const FETCH_ALL_ATTENDANCE_TYPES = 'FETCH_ALL_ATTENDANCE_TYPES'
export const FETCH_ALL_ATTENDANCE_TYPES_SUCCESS = 'FETCH_ALL_ATTENDANCE_TYPES_SUCCESS'
export const FETCH_ALL_ATTENDANCE_TYPES_ERROR = 'FETCH_ALL_ATTENDANCE_TYPES_ERROR'

export const GET_ATTENDANCE_TYPE_DATA = 'GET_ATTENDANCE_TYPE_DATA'
