export const FETCH_ALL_CALENDARS = 'FETCH_ALL_CALENDARS'
export const FETCH_ALL_CALENDARS_SUCCESS = 'FETCH_ALL_CALENDARS_SUCCESS'
export const FETCH_ALL_CALENDARS_ERROR = 'FETCH_ALL_CALENDARS_ERROR'

export const GET_CALENDAR_DATA = 'GET_CALENDAR_DATA'
export const GET_CALENDAR_FORM = 'GET_CALENDAR_FORM'

export const SET_CALENDAR_FORM = 'SET_CALENDAR_FORM'
export const RESET_CALENDAR_FORM = 'RESET_CALENDAR_FORM'
