export const FETCH_ALL_CALENDARS = 'FETCH_ALL_CALENDARS'
export const FETCH_ALL_CALENDARS_SUCCESS = 'FETCH_ALL_CALENDARS_SUCCESS'
export const FETCH_ALL_CALENDARS_ERROR = 'FETCH_ALL_CALENDARS_ERROR'

export const STORE_CALENDAR = 'STORE_CALENDAR'
export const STORE_CALENDAR_SUCCESS = 'STORE_CALENDAR_SUCCESS'
export const STORE_CALENDAR_ERROR = 'STORE_CALENDAR_ERROR'

export const FETCH_ONE_CALENDAR = 'FETCH_ONE_CALENDAR'
export const FETCH_ONE_CALENDAR_SUCCESS = 'FETCH_ONE_CALENDAR_SUCCESS'
export const FETCH_ONE_CALENDAR_ERROR = 'FETCH_ONE_CALENDAR_ERROR'

export const DESTROY_CALENDAR = 'DESTROY_CALENDAR'
export const DESTROY_CALENDAR_SUCCESS = 'DESTROY_CALENDAR_SUCCESS'
export const DESTROY_CALENDAR_ERROR = 'DESTROY_CALENDAR_ERROR'

export const GET_CALENDAR_DATA = 'GET_CALENDAR_DATA'
export const GET_CALENDAR_FORM = 'GET_CALENDAR_FORM'

export const SET_CALENDAR_FORM = 'SET_CALENDAR_FORM'
export const RESET_CALENDAR_FORM = 'RESET_CALENDAR_FORM'
