export const FETCH_ALL_ECHELONS = 'FETCH_ALL_ECHELONS'
export const FETCH_ALL_ECHELONS_SUCCESS = 'FETCH_ALL_ECHELONS_SUCCESS'
export const FETCH_ALL_ECHELONS_ERROR = 'FETCH_ALL_ECHELONS_ERROR'

export const FETCH_ONE_ECHELON = 'FETCH_ONE_ECHELON'
export const FETCH_ONE_ECHELON_SUCCESS = 'FETCH_ONE_ECHELON_SUCCESS'
export const FETCH_ONE_ECHELON_ERROR = 'FETCH_ONE_ECHELON_ERROR'

export const STORE_ECHELON = 'STORE_ECHELON'
export const STORE_ECHELON_SUCCESS = 'STORE_ECHELON_SUCCESS'
export const STORE_ECHELON_ERROR = 'STORE_ECHELON_ERROR'

export const UPDATE_ECHELON = 'UPDATE_ECHELON'
export const UPDATE_ECHELON_SUCCESS = 'UPDATE_ECHELON_SUCCESS'
export const UPDATE_ECHELON_ERROR = 'UPDATE_ECHELON_ERROR'

export const DESTROY_ECHELON = 'DESTROY_ECHELON'
export const DESTROY_ECHELON_SUCCESS = 'DESTROY_ECHELON_SUCCESS'
export const DESTROY_ECHELON_ERROR = 'DESTROY_ECHELON_ERROR'

export const GET_ECHELON_DATA = 'GET_ECHELON_DATA'
export const GET_ECHELON_FORM = 'GET_ECHELON_FORM'
export const SET_ECHELON_FORM = 'SET_ECHELON_FORM'
export const RESET_ECHELON_FORM = 'RESET_ECHELON_FORM'
