export const FETCH_ALL_ECHELON_TYPES = 'FETCH_ALL_ECHELON_TYPES'
export const FETCH_ALL_ECHELON_TYPES_SUCCESS = 'FETCH_ALL_ECHELON_TYPES_SUCCESS'
export const FETCH_ALL_ECHELON_TYPES_ERROR = 'FETCH_ALL_ECHELON_TYPES_ERROR'

export const GET_ECHELON_TYPE_DATA = 'GET_ECHELON_TYPE_DATA'
