// Mutations
export const SET_LOGGED_USER = 'SET_LOGGED_USER'
export const RESET_LOGGED_USER = 'RESET_LOGGED_USER'

// Getters
export const GET_LOGGED_USER = 'GET_LOGGED_USER'
export const GET_LOGGED_USER_NAME = 'GET_LOGGED_USER_NAME'
