// Mutations or actions
export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR'

export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER'
export const FETCH_LOGGED_USER_SUCCESS = 'FETCH_LOGGED_USER_SUCCESS'
export const FETCH_LOGGED_USER_ERROR = 'FETCH_LOGGED_USER_ERROR'

export const LOGOUT = 'LOGOUT'

export const SET_LOGGED_USER = 'SET_LOGGED_USER'
export const RESET_LOGGED_USER = 'RESET_LOGGED_USER'
export const RESET_LOGGED_USER_ERROR = 'RESET_LOGGED_USER_ERROR'

// Getters
export const GET_LOGGED_USER = 'GET_LOGGED_USER'
export const GET_LOGGED_USER_NAME = 'GET_LOGGED_USER_NAME'
