export const FETCH_ALL_RANKS = 'FETCH_ALL_RANKS'
export const FETCH_ALL_RANKS_SUCCESS = 'FETCH_ALL_RANKS_SUCCESS'
export const FETCH_ALL_RANKS_ERROR = 'FETCH_ALL_RANKS_ERROR'

export const FETCH_ONE_RANK = 'FETCH_ONE_RANK'
export const FETCH_ONE_RANK_SUCCESS = 'FETCH_ONE_RANK_SUCCESS'
export const FETCH_ONE_RANK_ERROR = 'FETCH_ONE_RANK_ERROR'

export const STORE_RANK = 'STORE_RANK'
export const STORE_RANK_SUCCESS = 'STORE_RANK_SUCCESS'
export const STORE_RANK_ERROR = 'STORE_RANK_ERROR'

export const GET_RANK_DATA = 'GET_RANK_DATA'
export const GET_RANK_FORM = 'GET_RANK_FORM'