export const FETCH_ALL_RANKS = 'FETCH_ALL_RANKS'
export const FETCH_ALL_RANKS_SUCCESS = 'FETCH_ALL_RANKS_SUCCESS'
export const FETCH_ALL_RANKS_ERROR = 'FETCH_ALL_RANKS_ERROR'

export const GET_RANK_DATA = 'GET_RANK_DATA'
export const GET_RANK_FORM = 'GET_RANK_FORM'