export const FETCH_ALL_RANKS = 'FETCH_ALL_RANKS'
export const FETCH_ALL_RANKS_SUCCESS = 'FETCH_ALL_RANKS_SUCCESS'
export const FETCH_ALL_RANKS_ERROR = 'FETCH_ALL_RANKS_ERROR'

export const FETCH_ONE_RANK = 'FETCH_ONE_RANK'
export const FETCH_ONE_RANK_SUCCESS = 'FETCH_ONE_RANK_SUCCESS'
export const FETCH_ONE_RANK_ERROR = 'FETCH_ONE_RANK_ERROR'

export const STORE_RANK = 'STORE_RANK'
export const STORE_RANK_SUCCESS = 'STORE_RANK_SUCCESS'
export const STORE_RANK_ERROR = 'STORE_RANK_ERROR'

export const UPDATE_RANK = 'UPDATE_RANK'
export const UPDATE_RANK_SUCCESS = 'UPDATE_RANK_SUCCESS'
export const UPDATE_RANK_ERROR = 'UPDATE_RANK_ERROR'

export const DESTROY_RANK = 'DESTROY_RANK'
export const DESTROY_RANK_SUCCESS = 'DESTROY_RANK_SUCCESS'
export const DESTROY_RANK_ERROR = 'DESTROY_RANK_ERROR'

export const GET_RANK_DATA = 'GET_RANK_DATA'

export const GET_RANK_FORM = 'GET_RANK_FORM'
export const SET_RANK_FORM = 'SET_RANK_FORM'
export const RESET_RANK_FORM = 'RESET_RANK_FORM'
