export const FETCH_ALL_TPP = 'FETCH_ALL_TPP'
export const FETCH_ALL_TPP_SUCCESS = 'FETCH_ALL_TPP_SUCCESS'
export const FETCH_ALL_TPP_ERROR = 'FETCH_ALL_TPP_ERROR'

export const STORE_TPP = 'STORE_TPP'
export const STORE_TPP_SUCCESS = 'STORE_TPP_SUCCESS'
export const STORE_TPP_ERROR = 'STORE_TPP_ERROR'

export const FETCH_ONE_TPP = 'FETCH_ONE_TPP'
export const FETCH_ONE_TPP_SUCCESS = 'FETCH_ONE_TPP_SUCCESS'
export const FETCH_ONE_TPP_ERROR = 'FETCH_ONE_TPP_ERROR'

export const UPDATE_TPP = 'UPDATE_TPP'
export const UPDATE_TPP_SUCCESS = 'UPDATE_TPP_SUCCESS'
export const UPDATE_TPP_ERROR = 'UPDATE_TPP_ERROR'

export const DESTROY_TPP = 'DESTROY_TPP'
export const DESTROY_TPP_SUCCESS = 'DESTROY_TPP_SUCCESS'
export const DESTROY_TPP_ERROR = 'DESTROY_TPP_ERROR'

export const GET_TPP_DATA = 'GET_TPP_DATA'
export const GET_TPP_FORM = 'GET_TPP_FORM'
export const SET_TPP_FORM = 'SET_TPP_FORM'
export const RESET_TPP_FORM = 'RESET_TPP_FORM'
