export const FETCH_ALL_WORKSHIFTS = 'FETCH_ALL_WORKSHIFTS'
export const FETCH_ALL_WORKSHIFTS_SUCCESS = 'FETCH_ALL_WORKSHIFTS_SUCCESS'
export const FETCH_ALL_WORKSHIFTS_ERROR = 'FETCH_ALL_WORKSHIFTS_ERROR'

export const STORE_WORKSHIFT = 'STORE_WORKSHIFT'
export const STORE_WORKSHIFT_SUCCESS = 'STORE_WORKSHIFT_SUCCESS'
export const STORE_WORKSHIFT_ERROR = 'STORE_WORKSHIFT_ERROR'

export const FETCH_ONE_WORKSHIFT = 'FETCH_ONE_WORKSHIFT'
export const FETCH_ONE_WORKSHIFT_SUCCESS = 'FETCH_ONE_WORKSHIFT_SUCCESS'
export const FETCH_ONE_WORKSHIFT_ERROR = 'FETCH_ONE_WORKSHIFT_ERROR'

export const UPDATE_WORKSHIFT = 'UPDATE_WORKSHIFT'
export const UPDATE_WORKSHIFT_SUCCESS = 'UPDATE_WORKSHIFT_SUCCESS'
export const UPDATE_WORKSHIFT_ERROR = 'UPDATE_WORKSHIFT_ERROR'

export const DESTROY_WORKSHIFT = 'DESTROY_WORKSHIFT'
export const DESTROY_WORKSHIFT_SUCCESS = 'DESTROY_WORKSHIFT_SUCCESS'
export const DESTROY_WORKSHIFT_ERROR = 'DESTROY_WORKSHIFT_ERROR'

export const GET_WORKSHIFT_DATA = 'GET_WORKSHIFT_DATA'
export const GET_WORKSHIFT_FORM = 'GET_WORKSHIFT_FORM'
export const SET_WORKSHIFT_FORM = 'SET_WORKSHIFT_FORM'
