export const FETCH_ALL_WORKSHIFTS = 'FETCH_ALL_WORKSHIFTS'
export const FETCH_ALL_WORKSHIFTS_SUCCESS = 'FETCH_ALL_WORKSHIFTS_SUCCESS'
export const FETCH_ALL_WORKSHIFTS_ERROR = 'FETCH_ALL_WORKSHIFTS_ERROR'

export const GET_WORKSHIFT_DATA = 'GET_WORKSHIFT_DATA'
